Repository GSG-G10/Crown-Ecommerce, pull requests merged in 2021-10, with the labels that each got.

#4 File structure
  .eslintrc.json
  .gitignore
  client/.gitignore
  client/.prettierrc
  client/.vscode/settings.json
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/components/index.js
  client/src/index.css
  client/src/index.js
  client/src/pages/index.js
  client/src/reportWebVitals.js
  client/src/setupTests.js
  client/src/utils/index.js
  package-lock.json
  package.json
  server/app.js
  server/controllers/index.js
  server/database/connection.js
  server/database/data/build.sql
  server/database/data/fakedata.sql
  server/database/queries/index.js
  server/index.js
  server/routes/index.js
  server/utils/index.js
Labels: Changes Requested

#12 fix structure
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/src/index.css
  client/src/index.js
  client/src/reportWebVitals.js
  client/src/setupTests.js
  package.json
Labels: Awaiting Review

#19 fix port and router
  .gitignore
  .vscode/settings.json
  client/package.json
  package.json
  server/app.js
  server/index.js
Labels: Awaiting Review

#18 create a database schema
  server/database/data/build.sql
Labels: Awaiting Review

#21 Fix Deploy
  client/.gitignore
Labels: Awaiting Review

#23 setup database connection
  server/database/connection.js
Labels: Awaiting Review

#31 26 fake data
  server/database/data/build.sql
  server/database/data/fakedata.sql
Labels: Awaiting Review

#33 Create Login Function
  package.json
  server/app.js
  server/controllers/loginUser.js
  server/database/connection.js
  server/database/data/build.sql
  server/database/queries/getHashPassword.js
  server/database/queries/loginQuery.js
  server/routes/index.js
  server/utils/jwt.js
  server/utils/validation/loginValidation.js
Labels: Awaiting Review

#45 Routerproduct
  server/controllers/get-product-id.js
  server/database/connection.js
  server/database/queries/get-product.js
  server/routes/index.js
  server/routes/product.js
Labels: Awaiting Review

#39 Search
  server/controllers/getDataPost.js
  server/database/data/build.sql
  server/database/queries/getDataPostQuery.js
  server/routes/index.js
Labels: Awaiting Review

#49 Fix sql injection
  server/database/queries/getDataPostQuery.js
Labels: Awaiting Review

#30 GET | Products | Backend
  server/controllers/getProducts.js
  server/controllers/index.js
  server/database/queries/getProducts.js
  server/database/queries/index.js
  server/routes/product.js
Labels: Done

#51 Footer
  client/src/App.js
  client/src/components/Footer/index.jsx
  client/src/components/Footer/style.css
  package-lock.json
  package.json
Labels: Awaiting Review

#59 router random products
  server/controllers/get-product-random.js
  server/controllers/index.js
  server/database/queries/get-product-random.js
  server/routes/product.js
Labels: Awaiting Review

#60 Get Product By Category
  server/controllers/getAllProducts.js
  server/database/data/fakedata.sql
  server/database/queries/getAllProducts.js
  server/database/queries/index.js
  server/routes/index.js
  server/routes/product.js
Labels: Awaiting Review

#69 10 home
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Card/index.js
  client/src/components/Card/style.css
  client/src/components/NewConfrts/style.css
Labels: Done

#47 Create Header Components
  client/src/App.js
  client/src/components/ApiCall.jsx
  client/src/components/Header/index.jsx
  client/src/components/Header/style.css
  client/src/index.js
  server/controllers/index.js
Labels: Awaiting Review
